site_name: Dynamic-Expressions
site_description: Build and execution dynamic expression
repo_url: https://github.com/waku-py/dynamic-expressions

nav:
  - About: about.md
  - Nodes and visitors: nodes.md
  - Dispatcher: dispatcher.md
  - Extensions: extensions.md
  - Cook Book: cookbook.md


theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select

  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      toggle:
        icon: material/brightness-4

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      toggle:
        icon: material/brightness-7

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_bases: false
            show_source: true
            show_root_toc_entry: false
