name: Publish Docs
on:
  push:
    branches:
      - main

env:
  COMMON_PYTHON_VERSION: '3.12.7'

jobs:
  docs:
    runs-on: ubuntu-latest

    env:
      DOCS_DEPLOY: true
      GITHUB_ACTIONS_AUTHOR_NAME: github-actions
      GITHUB_ACTIONS_AUTHOR_EMAIL: actions@users.noreply.github.com

    steps:
      - uses: actions/checkout@v4

      - name: Setup | Create access token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.VERSION_BUMPER_APPID }}
          private-key: ${{ secrets.VERSION_BUMPER_SECRET }}

      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup | Configure Git Credentials
        run: |
          git config user.name ${{ env.GITHUB_ACTIONS_AUTHOR_NAME }}
          git config user.email ${{ env.GITHUB_ACTIONS_AUTHOR_EMAIL }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.COMMON_PYTHON_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - run: uv run mkdocs gh-deploy --force
